#!/bin/bash

docker build \
    --build-arg BEANSTALKD_VERSION=$BEANSTALKD_VERSION \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=$SOURCE_COMMIT \
    --build-arg VCS_URL=`git config --get remote.origin.url` \
    -t $IMAGE_NAME:$BEANSTALKD_VERSION \
    -t $IMAGE_NAME .
